/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jnp.tmg.gui;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.CookieManager;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import jnp.tmg.client.CookiesManager;
import jnp.tmg.client.HttpRequester;
import jnp.tmg.modules.http.ContentType;
import jnp.tmg.modules.http.Cookie;
import jnp.tmg.modules.http.Header;
import jnp.tmg.modules.http.Headers;
import jnp.tmg.utils.BodyBuilder;
import jnp.tmg.utils.JsonUtils;
import jnp.tmg.utils.XMLUtils;

/**
 *
 * @author minht
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        myInitHomePage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        method_combobox = new javax.swing.JComboBox<>();
        url_string = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        btnParams = new javax.swing.JButton();
        RequestPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        HeaderTable = new javax.swing.JTable();
        AddRowHeaderButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        radioUrlencoded = new javax.swing.JRadioButton();
        radioRaw = new javax.swing.JRadioButton();
        cbRequestContentType = new javax.swing.JComboBox<>();
        rawPane = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBodyRequest = new javax.swing.JTextArea();
        urlencodedPane = new javax.swing.JLayeredPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        BodyTable = new javax.swing.JTable();
        AddRowBodyButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblResponseStatus = new javax.swing.JLabel();
        ResponsePane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHeaderResponse = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBodyResponse = new javax.swing.JTextArea();
        cbResponeContentType = new javax.swing.JComboBox<>();
        btnPreviewHtml = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CookiesTable = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        method_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GET", "POST", "PUT", "DELETE", "HEAD" }));

        url_string.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                url_stringActionPerformed(evt);
            }
        });

        SubmitButton.setText("Send");
        SubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitButtonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SubmitButtonMousePressed(evt);
            }
        });
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        btnParams.setText("Params");

        RequestPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        HeaderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(true), null, null}
            },
            new String [] {
                "", "Key", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        HeaderTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        HeaderTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(HeaderTable);
        if (HeaderTable.getColumnModel().getColumnCount() > 0) {
            HeaderTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            HeaderTable.getColumnModel().getColumn(1).setPreferredWidth(405);
            HeaderTable.getColumnModel().getColumn(2).setPreferredWidth(405);
        }

        AddRowHeaderButton.setText("+");
        AddRowHeaderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddRowHeaderButtonMouseClicked(evt);
            }
        });
        AddRowHeaderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRowHeaderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddRowHeaderButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(AddRowHeaderButton)
                .addContainerGap(226, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        RequestPane.addTab("Header", jPanel2);

        buttonGroup1.add(radioUrlencoded);
        radioUrlencoded.setText("x-www-form-urlencoded");

        buttonGroup1.add(radioRaw);
        radioRaw.setText("raw");

        cbRequestContentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "application/json", "text/xml", "application/xml", "text/html", "application/javascript", "text/plain" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioRaw, org.jdesktop.beansbinding.ELProperty.create("${selected}"), cbRequestContentType, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        txtBodyRequest.setColumns(20);
        txtBodyRequest.setRows(5);
        jScrollPane2.setViewportView(txtBodyRequest);

        rawPane.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout rawPaneLayout = new javax.swing.GroupLayout(rawPane);
        rawPane.setLayout(rawPaneLayout);
        rawPaneLayout.setHorizontalGroup(
            rawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                .addContainerGap())
        );
        rawPaneLayout.setVerticalGroup(
            rawPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rawPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        BodyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(true), null, null}
            },
            new String [] {
                "", "Key", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BodyTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        BodyTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BodyTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(BodyTable);
        if (BodyTable.getColumnModel().getColumnCount() > 0) {
            BodyTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            BodyTable.getColumnModel().getColumn(1).setPreferredWidth(405);
            BodyTable.getColumnModel().getColumn(2).setPreferredWidth(405);
        }

        AddRowBodyButton.setText("+");
        AddRowBodyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddRowBodyButtonMouseClicked(evt);
            }
        });
        AddRowBodyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRowBodyButtonActionPerformed(evt);
            }
        });

        urlencodedPane.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        urlencodedPane.setLayer(AddRowBodyButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout urlencodedPaneLayout = new javax.swing.GroupLayout(urlencodedPane);
        urlencodedPane.setLayout(urlencodedPaneLayout);
        urlencodedPaneLayout.setHorizontalGroup(
            urlencodedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlencodedPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddRowBodyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        urlencodedPaneLayout.setVerticalGroup(
            urlencodedPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(urlencodedPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(urlencodedPaneLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(AddRowBodyButton)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(radioUrlencoded)
                .addGap(18, 18, 18)
                .addComponent(radioRaw)
                .addGap(18, 18, 18)
                .addComponent(cbRequestContentType, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(urlencodedPane)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(rawPane)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioUrlencoded)
                    .addComponent(radioRaw)
                    .addComponent(cbRequestContentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(urlencodedPane)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(rawPane)
                    .addContainerGap()))
        );

        RequestPane.addTab("Body", jPanel3);

        jLabel3.setText("Type");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Auth", "Basic Auth", "OAuth 1.0", "OAuth 2.0" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(98, 98, 98)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        RequestPane.addTab("Authorization", jPanel1);

        jLabel1.setText("Response");

        jLabel2.setText("Status:");

        txtHeaderResponse.setColumns(20);
        txtHeaderResponse.setRows(5);
        jScrollPane3.setViewportView(txtHeaderResponse);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        ResponsePane.addTab("Header", jPanel5);

        txtBodyResponse.setColumns(20);
        txtBodyResponse.setRows(5);
        jScrollPane4.setViewportView(txtBodyResponse);

        cbResponeContentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- none -", "XML", "HTML", "JSON", "RAW" }));
        cbResponeContentType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbResponeContentTypeItemStateChanged(evt);
            }
        });
        cbResponeContentType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbResponeContentTypePropertyChange(evt);
            }
        });

        btnPreviewHtml.setText("Preview");
        btnPreviewHtml.setEnabled(false);
        btnPreviewHtml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewHtmlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbResponeContentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPreviewHtml)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbResponeContentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPreviewHtml))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ResponsePane.addTab("Body", jPanel6);

        CookiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Key", "Value", "Domain", "Path", "Expires", "HttpOnly", "Sercure"
            }
        ));
        CookiesTable.setRowHeight(40);
        CookiesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(CookiesTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ResponsePane.addTab("Cookies", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RequestPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(method_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(url_string)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnParams, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResponsePane, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(lblResponseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(method_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(url_string, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParams, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RequestPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResponseStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResponsePane, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblResponseStatus.getAccessibleContext().setAccessibleName("lblResponseStatus");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void url_stringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_url_stringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_url_stringActionPerformed

    private void SubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMouseClicked
        // TODO add your handling code here:
        String url = url_string.getText();
        String method = method_combobox.getSelectedItem().toString();
        if (null == method) {
            JOptionPane.showMessageDialog(null, "Select Method", "Method", ERROR);
            return;
        }
        System.out.println(url + method);
//         String[] key = new String[10];
//         String[] value = new String[10];

        try {
            requester = new HttpRequester(new URL(url));
            requester.setRequestHeaders(this.getRequestHeaders());
            requester.setBody(getRequestBody());

            switch (method) {
                case "GET":
                    requester.sendGet();
                    break;
                case "POST":
                    requester.sendPost();
                    break;
                case "PUSH":
                    requester.sendPut();
                    break;
                case "DELETE":
                    requester.sendDelete();
                    break;
                case "HEAD":
                    requester.sendHead();
                    break;
                default:
                    break;
            }

            loadResponseBody();
            loadResponseHeader();
            loadResponseCookies();

        } catch (IllegalArgumentException | MalformedURLException ex) {
            lblResponseStatus.setText("Error!!!");
            JOptionPane.showMessageDialog(null, "URL is not absolute!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            lblResponseStatus.setText("Error!!!");
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NullPointerException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SubmitButtonMouseClicked

    private void AddRowBodyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRowBodyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddRowBodyButtonActionPerformed

    private void AddRowBodyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRowBodyButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) BodyTable.getModel();
        model.addRow(new Object[]{true, "", ""});
    }//GEN-LAST:event_AddRowBodyButtonMouseClicked

    private void AddRowHeaderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddRowHeaderButtonMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) HeaderTable.getModel();
        model.addRow(new Object[]{true, "", ""});
    }//GEN-LAST:event_AddRowHeaderButtonMouseClicked

    private void AddRowHeaderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRowHeaderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddRowHeaderButtonActionPerformed

    private void cbResponeContentTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbResponeContentTypePropertyChange
        // TODO add your handling code here:


    }//GEN-LAST:event_cbResponeContentTypePropertyChange

    private void cbResponeContentTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbResponeContentTypeItemStateChanged
        // TODO add your handling code here:

        String bodyResponse = requester.getResponseBody();
        String contentType = cbResponeContentType.getSelectedItem().toString();
        if (null == contentType) {
            cbResponeContentType.setSelectedItem("RAW");
            //BodyResponse.setText(bodyResponse);

        } else {
            String parseData = "";
            switch (contentType) {
                case "HTML":
                case "XML": {
                    parseData = XMLUtils.prettyXMLJsoup(bodyResponse);
                }
                break;
                case "JSON": {
                    parseData = JsonUtils.prettyJson(bodyResponse);
                }
                break;
                case "Text":
                case "RAW":
                    parseData = bodyResponse;
                    break;
                default:
                    break;
            }
            txtBodyResponse.setText("");
            txtBodyResponse.append(parseData);
        }

    }//GEN-LAST:event_cbResponeContentTypeItemStateChanged

    private void btnPreviewHtmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewHtmlActionPerformed
        // TODO add your handling code here:
        previewBrowser();
    }//GEN-LAST:event_btnPreviewHtmlActionPerformed

    private void SubmitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitButtonMousePressed
        // TODO add your handling code here:
        resetRespones();
    }//GEN-LAST:event_SubmitButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRowBodyButton;
    private javax.swing.JButton AddRowHeaderButton;
    private javax.swing.JTable BodyTable;
    private javax.swing.JTable CookiesTable;
    private javax.swing.JTable HeaderTable;
    private javax.swing.JTabbedPane RequestPane;
    private javax.swing.JTabbedPane ResponsePane;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton btnParams;
    private javax.swing.JButton btnPreviewHtml;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbRequestContentType;
    private javax.swing.JComboBox<String> cbResponeContentType;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblResponseStatus;
    private javax.swing.JComboBox<String> method_combobox;
    private javax.swing.JRadioButton radioRaw;
    private javax.swing.JRadioButton radioUrlencoded;
    private javax.swing.JLayeredPane rawPane;
    private javax.swing.JTextArea txtBodyRequest;
    private javax.swing.JTextArea txtBodyResponse;
    private javax.swing.JTextArea txtHeaderResponse;
    private javax.swing.JTextField url_string;
    private javax.swing.JLayeredPane urlencodedPane;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    // 
    protected HttpRequester requester = null;

    protected void resetRespones() {
        lblResponseStatus.setText("Sending...");
        txtBodyResponse.setText("");
        txtHeaderResponse.setText("");
        try {
            cbResponeContentType.setSelectedIndex(0);
        } catch (Exception e) {
        }

    }

    protected Headers getRequestHeaders() {
        Headers requestHeaders = new Headers();
        String contentTypeStr = "";
        if (radioRaw.isSelected()) {
            contentTypeStr = "application/x-www-form-urlencoded";
        } else {
            contentTypeStr = cbRequestContentType.getSelectedItem().toString().trim();
        }
        requestHeaders.addEntity(new Header("Content-Type", contentTypeStr));
        for (int i = 0; i < HeaderTable.getRowCount(); ++i) {
            boolean isAdd = Boolean.valueOf(BodyTable.getValueAt(i, 0).toString());
            if (isAdd && HeaderTable.getValueAt(i, 0) != null && HeaderTable.getValueAt(i, 1) != null) {
                String key = HeaderTable.getValueAt(i, 1).toString();
                String value = HeaderTable.getValueAt(i, 2).toString();
                requestHeaders.addEntity(new Header(key, value));
            }
        }
        return requestHeaders;
    }

    protected String getRequestBody() {
        String body = "";
        if (radioUrlencoded.isSelected()) {
            Headers bodyKeysValues = new Headers();
            for (int i = 0; i < BodyTable.getRowCount(); ++i) {
                boolean isAdd = Boolean.valueOf(BodyTable.getValueAt(i, 0).toString());
                if (isAdd && BodyTable.getValueAt(i, 0) != null && BodyTable.getValueAt(i, 1) != null) {
                    String key = BodyTable.getValueAt(i, 1).toString();
                    String value = BodyTable.getValueAt(i, 2).toString();
                    bodyKeysValues.addEntity(new Header(key, value));
                }
            }

            try {
                body = new BodyBuilder()
                        .setContentType(ContentType.URLENC.toString())
                        .setKeysAndValues(bodyKeysValues)
                        .build();
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            body = txtBodyRequest.getText().trim();
        }
        System.out.println("RequestBody :" + body);
        return body;
    }

    protected void loadResponseHeader() {
        System.out.println("Load Response Headers...");

        txtHeaderResponse.setText(requester.getResponeHeaders().toString());
        lblResponseStatus.setText(requester.getStatusCode() + " - " + requester.getStatusMessage());
        System.out.println("Load Response Headers Completed.");
    }

    protected void loadResponseBody() {
        btnPreviewHtml.setEnabled(false);
        System.out.println("Load Response Body...");
        String ct = ContentType.ANY.toString();
        if (requester.getResponeHeaders().hasEntity("Content-Type")) {
            ct = requester.getResponeHeaders().getValue("Content-Type");
        }
        switch (ContentType.fromContentType(ct)) {
            case HTML:
                btnPreviewHtml.setEnabled(true);
                cbResponeContentType.setSelectedItem("HTML");
                break;
            case XML:
                cbResponeContentType.setSelectedItem("XML");
                break;
            case JSON:
                cbResponeContentType.setSelectedItem("JSON");
                break;
            default:
                cbResponeContentType.setSelectedItem("RAW");
        }
        System.out.println("Load Response Body Completed.");

    }

    protected void loadResponseCookies() {
        System.out.println("Load Response Cookies...");

        DefaultTableModel ctModel = (DefaultTableModel) CookiesTable.getModel();
        ctModel.getDataVector().removeAllElements();

        List<Cookie> listCookie = requester.getCookies().getEntities();
        CookiesManager.getInstance().addCookies(listCookie);
        for (Cookie c : listCookie) {
            Object[] col = new Object[7];
            col[0] = c.getKey();
            col[1] = c.getValue();
            col[2] = c.getDomain();
            col[3] = c.getPath();
            col[4] = c.getExpiryDate();
            col[5] = c.isHttpOnly();
            col[6] = c.isSecured();
            ctModel.addRow(col);
        }
        ctModel.fireTableDataChanged();
        System.out.println("Load Response Cookies Completed.");

    }

    protected void previewBrowser() {
        String bodyResponse = requester.getResponseBody();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectBrowser(bodyResponse).setVisible(true);
            }
        });
    }

    private void myInitHomePage() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        radioRaw.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (radioRaw.isSelected()) {
                    urlencodedPane.setVisible(false);
                    rawPane.setVisible(true);
                }
            }
        });

        radioUrlencoded.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (radioUrlencoded.isSelected()) {
                    urlencodedPane.setVisible(true);
                    rawPane.setVisible(false);
                }
            }
        });

        radioUrlencoded.setSelected(true);
    }
}
